### PR TITLE
week1

### PR DESCRIPTION
**Pull request by chiwenling**
完成 1-1 1-2

http://52.37.77.90:8000/api/attractions
http://52.37.77.90:8000/api/attractions?page=1
http://52.37.77.90:8000/api/attractions?page=1&keyword=山
http://52.37.77.90:8000/api/attraction/10
http://52.37.77.90:8000/api/mrts

### CODE REVIEW

**Comment by chiwenling** [comment]
我是紀玟伶

**Review by cwpeng — CHANGES_REQUESTED** [review]
- There should be no data in http://52.37.77.90:8000/api/attractions?page=3&keyword=%E5%B1%B1
- We should get more data in http://52.37.77.90:8000/api/attractions?page=0&keyword=%E5%8C%97
- Field names should align with API specifications.

**Comment by chiwenling** [comment]
修改
http://52.37.77.90:8000/api/attractions?page=0&keyword=北
http://52.37.77.90:8000/api/attractions?page=3&山
Field names

**Review by cwpeng — CHANGES_REQUESTED** [review]
- if we connect to http://52.37.77.90:8000/api/attractions?page=0&keyword=%E5%B1%B1, we get nextPage is null. So, there should be no data in the http://52.37.77.90:8000/api/attractions?page=1&keyword=%E5%B1%B1 or any page number greater than 0.
- Another example is: http://52.37.77.90:8000/api/attractions?page=1&keyword=%E5%8C%97

**Comment by chiwenling** [comment]
彭彭老師好
我是紀玟伶
修改分頁如下～謝謝

1.  page 0 : 
- http://52.37.77.90:8000/api/attractions?page=0&keyword=山

3. next page null : 
- http://52.37.77.90:8000/api/attractions?page=1&keyword=山

4. more data : 
- http://52.37.77.90:8000/api/attractions?page=0&keyword=北

**Comment by chiwenling** [comment]
week1 ＰＲ

**Comment by cwpeng** [comment]
Your server is down for now.

**Comment by chiwenling** [comment]
I run it again 

1. page 0 :
- http://52.37.77.90:8000/api/attractions?page=0&keyword=山

2. next page null :
- http://52.37.77.90:8000/api/attractions?page=1&keyword=山

3.more data :
- http://52.37.77.90:8000/api/attractions?page=0&keyword=北

**Comment by cwpeng** [comment]
Still cannot connect to your server. Try to make your server keep running even if you close the terminal.

**Comment by chiwenling** [comment]
sorry, I try it again. Thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
