### PR TITLE
week4 登入登出任務

### PR DESCRIPTION
**Pull request by chiwenling**
彭彭好：
我是紀玟伶
這是我的week4 登入登出任務
再請檢查，感謝！
http://52.37.77.90:8000/
http://52.37.77.90:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should check user sign-in status by calling User API, not just check localStorage in the front-end. (how about I put any text in localStorage through developer tools?)

**Comment by chiwenling** [comment]
老師，再麻煩檢查了，謝謝><

紀玟伶
http://52.37.77.90:8000/
http://52.37.77.90:8000/attraction/10

**Comment by chiwenling** [comment]
老師好：
更新連結如下，再麻煩老師檢查，謝謝
http://52.37.77.90:8000/
http://52.37.77.90:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your website.

**Comment by chiwenling** [comment]
sorry, i restart it again.
http://52.37.77.90:8000/
http://52.37.77.90:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Your attraction page always calls API for useless attraction list and mrt list.
- Your pages always call User Auth API twice. 1 time User Auth API call is enough to meet requirements.
- Could you tell me how you run your server in the background, so that even if you close the terminal to EC2 instance, your server will still alive.

**Comment by chiwenling** [comment]
老師好，第1和2點我再檢查看看，謝謝老師
另外，我的server只要終端機休眠就會連不上，我有嘗試延長他休眠的時間，但還是會出現 client_loop: send disconnect: Broken pipe ，不知道能不能請教老師給我些方向，感謝！

截圖 2024-07-04 上午1 03 48

截圖 2024-07-04 上午1 04 58

**Comment by cwpeng** [comment]
In week 1 guide, we have mentioned about how to run server in the background, so you should have learned and done it weeks ago. I recommend you read that guide carefully.

**Comment by chiwenling** [comment]
老師好：
我是玟伶，以下是修改的連結，
我重新用nohup開啟，再麻煩老師檢查，感謝感謝！

http://52.37.77.90:8000/
http://52.37.77.90:8000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
